import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import path from "node:path";
import { pathToFileURL } from "node:url";
import type { IconDefinition } from "../src/core/types";

const root = path.resolve(import.meta.dirname, "..");
const iconDir = path.join(root, "src/icons");
const generatedDir = path.join(root, "src/generated");
const svelteDir = path.join(root, "src/svelte/generated");

const files = (await readdir(iconDir)).filter((file) => file.endsWith(".ts")).sort();
const records: Array<{ file: string; id: string; icon: IconDefinition }> = [];

for (const file of files) {
  const module = await import(`${pathToFileURL(path.join(iconDir, file)).href}?t=${Date.now()}`);
  const icon = module.default as IconDefinition;
  const id = toIdentifier(icon.slug);
  records.push({ file, id, icon });
}

validate(records.map(({ icon }) => icon));
await mkdir(generatedDir, { recursive: true });
await rm(svelteDir, { recursive: true, force: true });
await mkdir(svelteDir, { recursive: true });

const imports = records.map(({ file, id }) => `import ${id} from "../icons/${file.replace(/\.ts$/, "")}";`).join("\n");
const names = records.map(({ id }) => id).join(", ");
const namedExports = records.map(({ id }) => `export { ${id} };`).join("\n");
await writeFile(
  path.join(generatedDir, "catalog.ts"),
  `/* Generated by scripts/generate.ts. Do not edit. */\n${imports}\n\n${namedExports}\n\nexport const icons = [${names}] as const;\nexport const iconsByName = Object.fromEntries(icons.map((icon) => [icon.exportName, icon])) as Record<string, (typeof icons)[number]>;\nexport const iconsBySlug = Object.fromEntries(icons.map((icon) => [icon.slug, icon])) as Record<string, (typeof icons)[number]>;\n`,
);

await writeFile(
  path.join(generatedDir, "react.ts"),
  `/* Generated by scripts/generate.ts. Do not edit. */\nimport { createReactIcon } from "../react/create-icon";\n${records.map(({ id }) => `import { ${id} } from "./catalog";`).join("\n")}\n\n${records.map(({ id, icon }) => `export const ${icon.exportName} = createReactIcon(${id});`).join("\n")}\n`,
);

await writeFile(
  path.join(generatedDir, "vue.ts"),
  `/* Generated by scripts/generate.ts. Do not edit. */\nimport { createVueIcon } from "../vue/create-icon";\n${records.map(({ id }) => `import { ${id} } from "./catalog";`).join("\n")}\n\n${records.map(({ id, icon }) => `export const ${icon.exportName} = createVueIcon(${id});`).join("\n")}\n`,
);

await writeFile(path.join(generatedDir, "styles.css"), `${getBaseCss()}\n\n${records.map(({ icon }) => `/* ${icon.name} */\n${icon.css}`).join("\n\n")}\n`);

for (const { id, icon } of records) {
  await writeFile(
    path.join(svelteDir, `${icon.exportName}.svelte`),
    `<script>\n  import MotionIcon from "../MotionIcon.svelte";\n  import { ${id} as definition } from "@hemaaanth/icons/core";\n  let props = $props();\n</script>\n\n<MotionIcon {definition} {...props} />\n`,
  );
}
await writeFile(
  path.join(root, "src/svelte/index.js"),
  `/* Generated by scripts/generate.ts. Do not edit. */\nexport { default as MotionIcon } from "./MotionIcon.svelte";\n${records.map(({ icon }) => `export { default as ${icon.exportName} } from "./generated/${icon.exportName}.svelte";`).join("\n")}\n`,
);

function toIdentifier(slug: string): string {
  return `${slug.replace(/-([a-z0-9])/g, (_, char: string) => char.toUpperCase())}Definition`;
}

function validate(icons: IconDefinition[]): void {
  const names = new Set<string>();
  const slugs = new Set<string>();
  for (const icon of icons) {
    if (names.has(icon.exportName)) throw new Error(`Duplicate export: ${icon.exportName}`);
    if (slugs.has(icon.slug)) throw new Error(`Duplicate slug: ${icon.slug}`);
    names.add(icon.exportName);
    slugs.add(icon.slug);
    if (icon.body.includes(".ic-") || icon.css.includes("--ic")) throw new Error(`${icon.slug} still uses the old namespace`);
    for (const knob of icon.knobs) {
      if (!icon.css.includes(knob.cssVar)) throw new Error(`${icon.slug} does not use ${knob.cssVar}`);
      const fallback = `${knob.cssVar}, ${knob.default}${knob.unit}`;
      if (!icon.css.includes(fallback)) throw new Error(`${icon.slug} metadata does not match CSS fallback ${fallback}`);
    }
  }
}

function getBaseCss(): string {
  return `/* Framework-neutral motion trigger. Import once in the consuming app. */
:root {
  --mi-time: 1;
  --mi-ease: cubic-bezier(0.32, 0.72, 0.24, 1);
  --mi-ease-spring: linear(0, 0.032 2%, 0.12 4%, 0.31 7%, 0.56 10.5%, 0.76 13.5%, 0.9 16.5%, 0.988 19.5%, 1.042 22.5%, 1.07 26%, 1.078 30%, 1.062 36%, 1.03 44%, 1.008 52%, 0.997 62%, 0.998 74%, 1);
  --mi-ease-pop: linear(0, 0.04 2%, 0.15 4.5%, 0.4 8%, 0.68 11.5%, 0.9 14.5%, 1.06 17.5%, 1.15 21%, 1.185 25%, 1.17 29.5%, 1.11 35.5%, 1.04 42%, 0.985 49%, 0.962 55.5%, 0.965 62%, 0.985 70%, 1.002 82%, 1);
  --mi-ease-bounce: linear(0, 0.2 5%, 0.65 11%, 1.05 17%, 1.35 22%, 1.52 26%, 1.55 29%, 1.44 34%, 1.2 41%, 1 48%, 0.88 55%, 0.86 59%, 0.92 66%, 1 74%, 1.04 81%, 1.01 90%, 1);
}

@media (hover: hover) {
  :where(button:not(:disabled), [role="button"]:not([aria-disabled="true"]), [role="menuitem"]:not([aria-disabled="true"]), [role="tab"]:not([aria-disabled="true"]), [role="option"]:not([aria-disabled="true"]), a:not([aria-disabled="true"]), summary:not([aria-disabled="true"]), label:not([aria-disabled="true"]), .mi-trigger:not([aria-disabled="true"])):hover .mi {
    --mi-progress: 1;
  }
}

:where(button:not(:disabled), [role="button"]:not([aria-disabled="true"]), [role="menuitem"]:not([aria-disabled="true"]), [role="tab"]:not([aria-disabled="true"]), [role="option"]:not([aria-disabled="true"]), a:not([aria-disabled="true"]), summary:not([aria-disabled="true"]), label:not([aria-disabled="true"]), .mi-trigger:not([aria-disabled="true"])):focus-visible .mi {
  --mi-progress: 1;
}

:where(button, [role="button"], [role="menuitem"], [role="tab"], [role="option"], a, summary, label, .mi-trigger):not(:hover):not(:focus-visible) .mi,
:where(button:disabled, [aria-disabled="true"]) .mi {
  --mi-progress: 0;
}

.mi-play .mi,
.mi.mi-play { --mi-progress: 1; }
.mi { overflow: visible; }
`;
}
